export const GALLERY_UI = {
  ko: {
    sectionLabel: '커뮤니티',
    title: '포토갤러리',
    all: '전체',
    yearSuffix: '년',
    countPrefix: '전체',
    countSuffix: '건',
    emptyYear: (year) => `${year}년 게시물이 없습니다`,
    emptyNone: '등록된 게시물이 없습니다',
    emptyBack: '전체 목록',
    emptyBackSuffix: '에서 다른 연도를 확인해 보세요.',
    filterAria: '연도별 필터',
    listAria: '갤러리 목록',
    heroAria: '주요 갤러리',
    paginationAria: '갤러리 페이지 탐색',
    prevPage: '이전 페이지',
    nextPage: '다음 페이지',
    home: '홈',
    crumbCurrent: '상세',
    crumbAria: '위치',
    author: '작성자',
    viewsByline: (n) => `조회\u00a0${n.toLocaleString()}`,
    next: '다음 글',
    prev: '이전 글',
    backToList: '목록으로',
    siblingAria: '이전·다음 글',
  },
  en: {
    sectionLabel: 'Community',
    title: 'Gallery',
    all: 'All',
    yearSuffix: '',
    countPrefix: '',
    countSuffix: ' posts',
    emptyYear: (year) => `No posts in ${year}`,
    emptyNone: 'No posts yet',
    emptyBack: 'All posts',
    emptyBackSuffix: ' to browse other years.',
    filterAria: 'Filter by year',
    listAria: 'Gallery list',
    heroAria: 'Featured gallery',
    paginationAria: 'Gallery pagination',
    prevPage: 'Previous page',
    nextPage: 'Next page',
    home: 'Home',
    crumbCurrent: 'Photo',
    crumbAria: 'Breadcrumb',
    author: 'Author',
    viewsByline: (n) => `${n.toLocaleString()} views`,
    next: 'Next',
    prev: 'Previous',
    backToList: 'Back to list',
    siblingAria: 'Previous and next posts',
  },
};

export function galleryUi(locale = 'ko') {
  return GALLERY_UI[locale] ?? GALLERY_UI.ko;
}
