export const PRESS_UI = {
  ko: {
    sectionLabel: '단체 활동',
    title: '언론보도',
    searchAria: '언론보도 검색',
    searchPlaceholder: '제목 또는 내용으로 검색',
    searchSubmit: '검색',
    emptySearchTitle: '검색 결과가 없습니다',
    emptySearchLead: (query) => `\u201c${query}\u201d에 해당하는 언론보도를 찾지 못했습니다.`,
    emptySearchHint: '다른 검색어를 입력하거나',
    emptySearchBack: '전체 목록',
    emptySearchBackSuffix: '을 확인하세요.',
    emptyNone: '등록된 언론보도가 없습니다',
    featured: '대표',
    featuredDetail: '대표 보도',
    published: (date) => `게재 ${date}`,
    excerptFallback: '요약이 없습니다. 상세에서 원문을 확인하세요.',
    secretExcerpt: '비밀 게시글입니다. 비밀번호 입력 후 내용을 확인할 수 있습니다.',
    home: '홈',
    crumbCurrent: '상세',
    crumbAria: '위치',
    source: '언론사',
    publishedOn: '게재일',
    registeredOn: '등록일',
    views: '조회',
    readOriginal: '원문 기사 보기',
    externalNote: '외부 사이트로 이동합니다.',
    next: '다음 글',
    prev: '이전 글',
    backToList: '목록으로',
    siblingAria: '이전·다음 글',
    metaUnit: 'posts',
  },
  en: {
    sectionLabel: 'Activities',
    title: 'Press',
    searchAria: 'Search press coverage',
    searchPlaceholder: 'Search titles or content',
    searchSubmit: 'Search',
    emptySearchTitle: 'No results',
    emptySearchLead: (query) => `No press coverage matching \u201c${query}\u201d.`,
    emptySearchHint: 'Try another search or see',
    emptySearchBack: 'all articles',
    emptySearchBackSuffix: '.',
    emptyNone: 'No press coverage yet',
    featured: 'Featured',
    featuredDetail: 'Featured',
    published: (date) => `Published ${date}`,
    excerptFallback: 'No summary. Open the article for the original.',
    secretExcerpt: 'This is a private post. Enter the password to view it.',
    home: 'Home',
    crumbCurrent: 'Article',
    crumbAria: 'Breadcrumb',
    source: 'Outlet',
    publishedOn: 'Published',
    registeredOn: 'Posted',
    views: 'Views',
    readOriginal: 'Read original article',
    externalNote: 'Opens an external site.',
    next: 'Next',
    prev: 'Previous',
    backToList: 'Back to list',
    siblingAria: 'Previous and next posts',
    metaUnit: 'articles',
  },
};

export function pressUi(locale = 'ko') {
  return PRESS_UI[locale] ?? PRESS_UI.ko;
}
