export const WR_NEWS_UI = {
  ko: {
    sectionLabel: '단체 활동',
    title: 'WR뉴스',
    searchAria: 'WR뉴스 검색',
    searchPlaceholder: '제목 또는 내용으로 검색',
    searchSubmit: '검색',
    emptyTitle: '등록된 게시물이 없습니다',
    emptySearch: '검색 결과가 없습니다',
    emptyBack: '전체 목록',
    emptyBackSuffix: '으로 돌아가 보세요.',
    views: (n) => `조회 ${n.toLocaleString()}`,
    home: '홈',
    crumbCurrent: '상세',
    author: '작성자',
    viewsByline: (n) => `조회\u00a0${n.toLocaleString()}`,
    next: '다음 글',
    prev: '이전 글',
    backToList: '목록으로',
    siblingAria: '이전·다음 글',
    listAria: 'WR뉴스 목록',
    metaSearch: (query, count) => ({
      prefix: '',
      query,
      mid: '검색 결과',
      count,
      suffix: '건',
      clear: '초기화',
      clearAria: '검색 초기화',
    }),
    metaAll: (count) => ({ before: '전체', count, after: '건' }),
    paginationAria: '페이지 탐색',
    prevPage: '이전 페이지',
    nextPage: '다음 페이지',
  },
  en: {
    sectionLabel: 'Activities',
    title: 'WR News',
    searchAria: 'Search WR News',
    searchPlaceholder: 'Search titles or content',
    searchSubmit: 'Search',
    emptyTitle: 'No posts yet',
    emptySearch: 'No matching posts',
    emptyBack: 'All posts',
    emptyBackSuffix: '.',
    views: (n) => `${n.toLocaleString()} views`,
    home: 'Home',
    crumbCurrent: 'Article',
    author: 'Author',
    viewsByline: (n) => `${n.toLocaleString()} views`,
    next: 'Next',
    prev: 'Previous',
    backToList: 'Back to list',
    siblingAria: 'Previous and next posts',
    listAria: 'WR News list',
    metaSearch: (query, count) => ({
      prefix: '',
      query,
      mid: 'Results',
      count,
      suffix: '',
      clear: 'Clear',
      clearAria: 'Clear search',
    }),
    metaAll: (count) => ({ before: '', count, after: 'posts' }),
    paginationAria: 'Pagination',
    prevPage: 'Previous page',
    nextPage: 'Next page',
  },
};

export function wrNewsUi(locale = 'ko') {
  return WR_NEWS_UI[locale] ?? WR_NEWS_UI.ko;
}
